### ISSUE TITLE
[Security] Workflow changelog.yml is using vulnerable action Zomzog/changelog-checker

### ISSUE THREAD

**Issue by igibek** [ocular-d/vuepress-demo#32]
The workflow changelog.yml is referencing action Zomzog/changelog-checker using references v1.0.0. However this reference is missing the commit [18a8a132efd34b5fc0ec6f29272fa6f6d662f48d](https://github.com/Zomzog/changelog-checker/commits/18a8a132efd34b5fc0ec6f29272fa6f6d662f48d) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by svx** [comment]
Thanks! Updated!
